os:
  - linux
language: node_js
node_js:
  - '10.16.3'
services:
  - docker
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm install -g npm
  - docker run --name some-mysql3 -e MYSQL_ROOT_PASSWORD=123456 -e MYSQL_DATABASE=sepa_desarrollo mysql
install:
  - yarn
script:
  - npm test
